/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/v1/agents/{agent_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Version */
        get: operations["get_agent_version_v1_agents__agent_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent
         * @description Blocking run — the same AgentRuntime.run() the SSE route drives.
         */
        post: operations["run_agent_v1_agents__agent_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Agent
         * @description SSE run: subscribe before the run starts, then frame every event.
         *     Resume with `Last-Event-ID` (durable cursor) plus `run_id` in the body;
         *     a finished run replays from the DB, a live one from its sink. The stream
         *     ends with the run's single terminal event.
         */
        post: operations["stream_agent_v1_agents__agent_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_v1_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_v1_executions__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Idempotent: triggers the live run's token; a finished run is a no-op
         *     that reports its current status.
         */
        post: operations["cancel_run_v1_executions__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_executions__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{agent_id}/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversation Messages */
        get: operations["conversation_messages_v1_conversations__agent_id___session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentDefinition */
        AgentDefinition: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            model: components["schemas"]["ModelRef"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** User Prompt Template */
            user_prompt_template?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolBinding"][];
            strategy: components["schemas"]["StrategyConfig"];
            memory?: components["schemas"]["MemoryConfig"];
            /**
             * Max Iterations
             * @default 8
             */
            max_iterations: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** AgentDetail */
        AgentDetail: {
            definition: components["schemas"]["AgentDefinition"];
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** AgentList */
        AgentList: {
            /** Items */
            items: components["schemas"]["AgentDefinition"][];
        };
        /**
         * AgentUpsertRequest
         * @description Partial create/update payload — everything except name/model/strategy
         *     is optional and falls back to the AgentDefinition defaults.
         */
        AgentUpsertRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            model?: components["schemas"]["ModelRef"] | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** User Prompt Template */
            user_prompt_template?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolBinding"][] | null;
            strategy?: components["schemas"]["StrategyConfig"] | null;
            memory?: components["schemas"]["MemoryConfig"] | null;
            /** Max Iterations */
            max_iterations?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AgentVersion
         * @description Immutable, append-only snapshot of an AgentDefinition.
         *
         *     `snapshot` is the replay source of truth for every execution that
         *     references this version (ADR 0002: snapshot-vs-reference).
         */
        AgentVersion: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Version */
            version: number;
            snapshot: components["schemas"]["AgentDefinition"];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CancelResult */
        CancelResult: {
            /** Run Id */
            run_id: string;
            /** Cancelled */
            cancelled: boolean;
            /** Status */
            status: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["SectionCapability"];
            };
        };
        /**
         * CursorEvent
         * @description One replayed event tagged with its durable cursor (SSE Last-Event-ID
         *     space), so JSON replay can drive exactly-once clients too.
         */
        CursorEvent: {
            /** Cursor */
            cursor: number;
            /** Event */
            event: components["schemas"]["RunStarted"] | components["schemas"]["IterationStarted"] | components["schemas"]["ModelInvocationStarted"] | components["schemas"]["TextDelta"] | components["schemas"]["ModelInvocationCompleted"] | components["schemas"]["ToolCallRequested"] | components["schemas"]["ToolCallStarted"] | components["schemas"]["ToolCallCompleted"] | components["schemas"]["ToolCallFailed"] | components["schemas"]["IterationCompleted"] | components["schemas"]["RunCompleted"] | components["schemas"]["RunFailed"] | components["schemas"]["RunCancelled"];
        };
        /** EventList */
        EventList: {
            /** Run Id */
            run_id: string;
            /** After */
            after?: number | null;
            /** Events */
            events: components["schemas"]["CursorEvent"][];
        };
        /** ExecutionDetail */
        ExecutionDetail: {
            run: components["schemas"]["RunResult"];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Tool Executions */
            tool_executions: components["schemas"]["ToolResult"][];
        };
        /** ExecutionList */
        ExecutionList: {
            /** Items */
            items: components["schemas"]["RunResult"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImagePart
         * @description Reserved for multimodal phases; not produced by Phase 1 code.
         */
        ImagePart: {
            /**
             * Type
             * @default image
             * @constant
             */
            type: "image";
            /** Url */
            url: string;
        };
        /** IterationCompleted */
        IterationCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iteration.completed";
            /** Iteration */
            iteration: number;
            usage: components["schemas"]["Usage"];
        };
        /** IterationStarted */
        IterationStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iteration.started";
            /** Iteration */
            iteration: number;
        };
        /** MemoryConfig */
        MemoryConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Max Messages
             * @default 20
             */
            max_messages: number;
            /** Session Key */
            session_key?: string | null;
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "developer" | "user" | "assistant" | "tool";
            /**
             * Content
             * @default
             */
            content: string | (components["schemas"]["TextPart"] | components["schemas"]["ImagePart"])[];
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][] | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** MessageList */
        MessageList: {
            /** Agent Id */
            agent_id: string;
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /** ModelInvocationCompleted */
        ModelInvocationCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "model.invocation.completed";
            usage: components["schemas"]["Usage"];
            /** Finish Reason */
            finish_reason: string;
            /** Model */
            model: string;
        };
        /** ModelInvocationStarted */
        ModelInvocationStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "model.invocation.started";
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
        };
        /**
         * ModelListResponse
         * @description Live catalog from a provider endpoint (ADR 0007) — what the endpoint
         *     answered, not a configured fact.
         */
        ModelListResponse: {
            /** Provider */
            provider: string;
            /** Base Url */
            base_url?: string | null;
            /** Models */
            models: string[];
        };
        /**
         * ModelRef
         * @description Reference to a model. `api_key_env` names an environment variable —
         *     the secret itself never enters the domain.
         */
        ModelRef: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
        };
        /** RunCancelled */
        RunCancelled: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled";
            /** Reason */
            reason: string;
            total_usage: components["schemas"]["Usage"];
        };
        /** RunCompleted */
        RunCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.completed";
            /** Final Message */
            final_message: string;
            total_usage: components["schemas"]["Usage"];
            /** Iterations */
            iterations: number;
        };
        /** RunFailed */
        RunFailed: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.failed";
            /** Error */
            error: string;
            /**
             * Error Kind
             * @enum {string}
             */
            error_kind: "max_iterations" | "timeout" | "model" | "tool" | "output_schema";
            total_usage: components["schemas"]["Usage"];
        };
        /**
         * RunRequest
         * @description Body for /run and /stream. `run_id` is stream-resume only: attach to
         *     an existing run's stream instead of starting a new one.
         */
        RunRequest: {
            /** Input */
            input: string;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Variables */
            variables?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** Run Id */
            run_id: string;
            /** Agent Id */
            agent_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled" | "timed_out";
            /**
             * Input
             * @default
             */
            input: string;
            /**
             * Agent Version Id
             * @default
             */
            agent_version_id: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /** Final Message */
            final_message?: string | null;
            total_usage?: components["schemas"]["Usage"];
            /**
             * Iterations
             * @default 0
             */
            iterations: number;
            /** Error */
            error?: string | null;
            /** Error Kind */
            error_kind?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /** Event Cursor */
            event_cursor?: number | null;
        };
        /** RunStarted */
        RunStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
            /** Agent Id */
            agent_id: string;
            /** Agent Version Id */
            agent_version_id: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Input
             * @default
             */
            input: string;
        };
        /**
         * SectionCapability
         * @description One IA section's enablement fact (F1). Disabled sections always carry
         *     the `stage` that will enable them; `detail` carries derived facts
         *     (registries mirror registries — never hardcoded).
         */
        SectionCapability: {
            /** Enabled */
            enabled: boolean;
            /** Mode */
            mode?: string | null;
            /** Summary */
            summary?: string | null;
            /** Stage */
            stage?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /** StrategyConfig */
        StrategyConfig: {
            /**
             * Type
             * @enum {string}
             */
            type: "function_calling" | "react";
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** TextDelta */
        TextDelta: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text.delta";
            /** Text */
            text: string;
        };
        /** TextPart */
        TextPart: {
            /**
             * Type
             * @default text
             * @constant
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** ToolBinding */
        ToolBinding: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ToolCallCompleted */
        ToolCallCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.completed";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /**
             * Output
             * @default
             */
            output: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** ToolCallFailed */
        ToolCallFailed: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.failed";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /** Error */
            error: string;
            /**
             * Kind
             * @default internal
             * @enum {string}
             */
            kind: "validation" | "timeout" | "internal";
        };
        /** ToolCallRequested */
        ToolCallRequested: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.requested";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ToolCallStarted */
        ToolCallStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.started";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Output */
            output: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** Usage */
        Usage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /** Extra */
            extra?: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Version */
            version: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_v1_agents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_version_v1_agents__agent_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_v1_agents__agent_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_agent_v1_agents__agent_id__stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_executions_v1_executions_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
                status?: ("running" | "succeeded" | "failed" | "cancelled" | "timed_out") | null;
                session_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_v1_executions__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_executions__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_executions__run_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_messages_v1_conversations__agent_id___session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                agent_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query: {
                provider: string;
                base_url?: string | null;
                api_key_env?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
