/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/v1/agents/{agent_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Version */
        get: operations["get_agent_version_v1_agents__agent_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Agent
         * @description Blocking run — enqueue, then wait for the worker's segment to end. The
         *     subscribe replays anything the worker already wrote, so there is no race
         *     between enqueueing and listening. A pause (S10) ends the segment like a
         *     terminal: the route returns the awaiting_input row and the client
         *     resumes with POST /executions/{id}/resume.
         */
        post: operations["run_agent_v1_agents__agent_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Agent
         * @description SSE run: enqueue, then frame every event the worker writes. Resume with
         *     `Last-Event-ID` (durable cursor) plus `run_id` in the body — replay and
         *     live tail are the same cursor space (PgEventStream tails the DB, so the
         *     stream survives this process). Ends with the segment's last event
         *     (terminal or pause, S10): a pause closes the stream and the client
         *     resumes with POST /executions/{id}/resume.
         */
        post: operations["stream_agent_v1_agents__agent_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_v1_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_v1_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_v1_executions__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Idempotent. A run live in THIS process gets its runtime token; a
         *     queued or foreign-worker run gets a cross-process cancel request
         *     (ADR 0008 §6) that the owning worker's heartbeat pops. A paused run
         *     (S10) is finished directly — no heartbeat holds it — on the same
         *     append-terminal-and-finish path the reaper uses, so cancelling an
         *     awaiting_input run is immediate, not cooperative. A finished run is a
         *     no-op that reports its current status.
         */
        post: operations["cancel_run_v1_executions__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Run
         * @description Human-in-the-loop resume (S10, ADR 0010 §4): merge the answer into
         *     the paused run's queue payload and block until the resumed segment ends
         *     (like /run). A segment can pause again — the route then returns the
         *     still-awaiting row and the client answers the next question.
         */
        post: operations["resume_run_v1_executions__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_executions__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_v1_members_get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_v1_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Member */
        delete: operations["delete_member_v1_members__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_v1_members__user_id__patch"];
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_v1_api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Idempotent-by-id: revoking an already-revoked key is a no-op.
         */
        delete: operations["revoke_api_key_v1_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Credentials */
        get: operations["list_credentials_v1_credentials_get"];
        put?: never;
        /** Create Credential */
        post: operations["create_credential_v1_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Credential */
        delete: operations["revoke_credential_v1_credentials__credential_id__delete"];
        options?: never;
        head?: never;
        /** Update Credential */
        patch: operations["update_credential_v1_credentials__credential_id__patch"];
        trace?: never;
    };
    "/v1/conversations/{agent_id}/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversation Messages */
        get: operations["conversation_messages_v1_conversations__agent_id___session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentDefinition */
        AgentDefinition: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            model: components["schemas"]["ModelRef"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /** User Prompt Template */
            user_prompt_template?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolBinding"][];
            strategy: components["schemas"]["StrategyConfig"];
            memory?: components["schemas"]["MemoryConfig"];
            /**
             * Max Iterations
             * @default 8
             */
            max_iterations: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** AgentDetail */
        AgentDetail: {
            definition: components["schemas"]["AgentDefinition"];
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** AgentList */
        AgentList: {
            /** Items */
            items: components["schemas"]["AgentDefinition"][];
        };
        /**
         * AgentUpsertRequest
         * @description Partial create/update payload — everything except name/model/strategy
         *     is optional and falls back to the AgentDefinition defaults.
         */
        AgentUpsertRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            model?: components["schemas"]["ModelRef"] | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** User Prompt Template */
            user_prompt_template?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolBinding"][] | null;
            strategy?: components["schemas"]["StrategyConfig"] | null;
            memory?: components["schemas"]["MemoryConfig"] | null;
            /** Max Iterations */
            max_iterations?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AgentVersion
         * @description Immutable, append-only snapshot of an AgentDefinition.
         *
         *     `snapshot` is the replay source of truth for every execution that
         *     references this version (ADR 0002: snapshot-vs-reference).
         */
        AgentVersion: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Version */
            version: number;
            snapshot: components["schemas"]["AgentDefinition"];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /** Name */
            name: string;
        };
        /**
         * ApiKeyCreated
         * @description Create-time response: the ONLY response that ever carries the
         *     plaintext key (`plaintext`), alongside its stored metadata.
         */
        ApiKeyCreated: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Plaintext */
            plaintext: string;
            /** Created At */
            created_at?: string | null;
        };
        /** ApiKeyList */
        ApiKeyList: {
            /** Items */
            items: components["schemas"]["ApiKeyOut"][];
        };
        /**
         * ApiKeyOut
         * @description Metadata only — no plaintext, no hash; `key_prefix` is display form.
         */
        ApiKeyOut: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Created At */
            created_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
        };
        /** CancelResult */
        CancelResult: {
            /** Run Id */
            run_id: string;
            /** Cancelled */
            cancelled: boolean;
            /** Status */
            status: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["SectionCapability"];
            };
        };
        /**
         * CredentialCreate
         * @description POST /credentials — `secret` is the BYOK key material. It is
         *     encrypted server-side and never stored or returned in plaintext
         *     (ADR 0006 §7).
         */
        CredentialCreate: {
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Secret */
            secret: string;
        };
        /** CredentialList */
        CredentialList: {
            /** Items */
            items: components["schemas"]["CredentialOut"][];
        };
        /**
         * CredentialOut
         * @description Metadata only — NO ciphertext, NO secret. The AES-GCM envelope never
         *     crosses the API (ADR 0006 §7).
         */
        CredentialOut: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
        };
        /** CredentialPatch */
        CredentialPatch: {
            /** Name */
            name?: string | null;
            /** Secret */
            secret?: string | null;
        };
        /**
         * CursorEvent
         * @description One replayed event tagged with its durable cursor (SSE Last-Event-ID
         *     space), so JSON replay can drive exactly-once clients too.
         */
        CursorEvent: {
            /** Cursor */
            cursor: number;
            /** Event */
            event: components["schemas"]["RunStarted"] | components["schemas"]["IterationStarted"] | components["schemas"]["ModelInvocationStarted"] | components["schemas"]["TextDelta"] | components["schemas"]["ModelInvocationCompleted"] | components["schemas"]["ToolCallRequested"] | components["schemas"]["ToolCallStarted"] | components["schemas"]["ToolCallCompleted"] | components["schemas"]["ToolCallFailed"] | components["schemas"]["IterationCompleted"] | components["schemas"]["RunAwaitingInput"] | components["schemas"]["RunCompleted"] | components["schemas"]["RunFailed"] | components["schemas"]["RunCancelled"];
        };
        /**
         * EnvCredentialRef
         * @description Credential reference: the *name* of an environment variable — the
         *     secret itself never enters the domain (D18, ADR 0005).
         */
        EnvCredentialRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "env";
            /** Env Var */
            env_var: string;
        };
        /** EventList */
        EventList: {
            /** Run Id */
            run_id: string;
            /** After */
            after?: number | null;
            /** Events */
            events: components["schemas"]["CursorEvent"][];
        };
        /** ExecutionDetail */
        ExecutionDetail: {
            run: components["schemas"]["RunResult"];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Tool Executions */
            tool_executions: components["schemas"]["ToolResult"][];
        };
        /** ExecutionList */
        ExecutionList: {
            /** Items */
            items: components["schemas"]["RunResult"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImagePart
         * @description Reserved for multimodal phases; not produced by Phase 1 code.
         */
        ImagePart: {
            /**
             * Type
             * @default image
             * @constant
             */
            type: "image";
            /** Url */
            url: string;
        };
        /** IterationCompleted */
        IterationCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iteration.completed";
            /** Iteration */
            iteration: number;
            usage: components["schemas"]["Usage"];
        };
        /** IterationStarted */
        IterationStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iteration.started";
            /** Iteration */
            iteration: number;
        };
        /**
         * LoginRequest
         * @description Body for /auth/login. Plain string email — validation parity with
         *     members invites, no email-validator dependency.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MemberCreate
         * @description POST /members. `password` is optional — a keys-only member carries no
         *     password hash and cannot log in until one is set.
         */
        MemberCreate: {
            /** Email */
            email: string;
            /** Password */
            password?: string | null;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** MemberList */
        MemberList: {
            /** Items */
            items: components["schemas"]["MemberOut"][];
        };
        /**
         * MemberOut
         * @description A member of the tenant — deliberately no password_hash field; the
         *     scrypt string never crosses the API.
         */
        MemberOut: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Email */
            email: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Role */
            role: string;
            /** Created At */
            created_at?: string | null;
        };
        /** MemberPatch */
        MemberPatch: {
            /** Display Name */
            display_name?: string | null;
            /** Role */
            role?: string | null;
        };
        /** MemoryConfig */
        MemoryConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Max Messages
             * @default 20
             */
            max_messages: number;
            /** Session Key */
            session_key?: string | null;
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "developer" | "user" | "assistant" | "tool";
            /**
             * Content
             * @default
             */
            content: string | (components["schemas"]["TextPart"] | components["schemas"]["ImagePart"])[];
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][] | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** MessageList */
        MessageList: {
            /** Agent Id */
            agent_id: string;
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /** ModelInvocationCompleted */
        ModelInvocationCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "model.invocation.completed";
            usage: components["schemas"]["Usage"];
            /** Finish Reason */
            finish_reason: string;
            /** Model */
            model: string;
        };
        /** ModelInvocationStarted */
        ModelInvocationStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "model.invocation.started";
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
        };
        /**
         * ModelListResponse
         * @description Live catalog from a provider endpoint (ADR 0007) — what the endpoint
         *     answered, not a configured fact.
         */
        ModelListResponse: {
            /** Provider */
            provider: string;
            /** Base Url */
            base_url?: string | null;
            /** Models */
            models: string[];
        };
        /**
         * ModelRef
         * @description Reference to a model. `credential_ref` is a *reference* (env-var name
         *     or stored credential id) — credential material never enters the domain,
         *     a snapshot, or an API response (ADR 0006 §1).
         */
        ModelRef: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Credential Ref */
            credential_ref?: (components["schemas"]["EnvCredentialRef"] | components["schemas"]["StoredCredentialRef"]) | null;
        };
        /**
         * ResumeBody
         * @description Body for POST /executions/{id}/resume (S10, ADR 0010 §4; ADR 0011):
         *     an ask_human pause answers with `content`; a tool-approval pause answers
         *     with `tool_approval` (batch shorthand) or `decisions` (per-call
         *     verdicts — calls absent from the map are declined, ADR 0011). Exactly
         *     one is present.
         */
        ResumeBody: {
            /** Content */
            content?: string | null;
            /** Tool Approval */
            tool_approval?: boolean | null;
            /** Decisions */
            decisions?: {
                [key: string]: boolean;
            } | null;
        };
        /**
         * RunAwaitingInput
         * @description The run paused for a human decision. NOT terminal — exactly-one-
         *     terminal still holds for the whole run; the pause ends one *segment* of
         *     the gapless sequence (no non-terminal event may follow it within a
         *     segment; the next event belongs to the resumed segment).
         */
        RunAwaitingInput: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.awaiting_input";
            /**
             * Reason
             * @enum {string}
             */
            reason: "tool_approval" | "strategy";
            /**
             * Question
             * @default
             */
            question: string;
            /** Pending Calls */
            pending_calls?: components["schemas"]["ToolCall"][];
            /**
             * Awaiting Until
             * Format: date-time
             */
            awaiting_until: string;
        };
        /** RunCancelled */
        RunCancelled: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled";
            /** Reason */
            reason: string;
            total_usage: components["schemas"]["Usage"];
        };
        /** RunCompleted */
        RunCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.completed";
            /** Final Message */
            final_message: string;
            total_usage: components["schemas"]["Usage"];
            /** Iterations */
            iterations: number;
        };
        /** RunFailed */
        RunFailed: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.failed";
            /** Error */
            error: string;
            /**
             * Error Kind
             * @enum {string}
             */
            error_kind: "max_iterations" | "timeout" | "model" | "tool" | "output_schema";
            total_usage: components["schemas"]["Usage"];
        };
        /**
         * RunRequest
         * @description Body for /run and /stream. `run_id` is stream-resume only: attach to
         *     an existing run's stream instead of starting a new one.
         */
        RunRequest: {
            /** Input */
            input: string;
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Variables */
            variables?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** Run Id */
            run_id: string;
            /** Agent Id */
            agent_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_input" | "succeeded" | "failed" | "cancelled" | "timed_out";
            /**
             * Input
             * @default
             */
            input: string;
            /**
             * Agent Version Id
             * @default
             */
            agent_version_id: string;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /** Final Message */
            final_message?: string | null;
            total_usage?: components["schemas"]["Usage"];
            /**
             * Iterations
             * @default 0
             */
            iterations: number;
            /** Error */
            error?: string | null;
            /** Error Kind */
            error_kind?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /** Event Cursor */
            event_cursor?: number | null;
        };
        /** RunStarted */
        RunStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
            /** Agent Id */
            agent_id: string;
            /** Agent Version Id */
            agent_version_id: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Input
             * @default
             */
            input: string;
        };
        /**
         * SectionCapability
         * @description One IA section's enablement fact (F1). Disabled sections always carry
         *     the `stage` that will enable them; `detail` carries derived facts
         *     (registries mirror registries — never hardcoded).
         */
        SectionCapability: {
            /** Enabled */
            enabled: boolean;
            /** Mode */
            mode?: string | null;
            /** Summary */
            summary?: string | null;
            /** Stage */
            stage?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StoredCredentialRef
         * @description Credential reference: a stored (BYOK) credential id, tenant-scoped at
         *     resolution time (ADR 0006). An id alone is never authorization.
         */
        StoredCredentialRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stored";
            /** Credential Id */
            credential_id: string;
        };
        /** StrategyConfig */
        StrategyConfig: {
            /**
             * Type
             * @enum {string}
             */
            type: "function_calling" | "react";
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** TextDelta */
        TextDelta: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text.delta";
            /** Text */
            text: string;
        };
        /** TextPart */
        TextPart: {
            /**
             * Type
             * @default text
             * @constant
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** ToolBinding */
        ToolBinding: {
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ToolCallCompleted */
        ToolCallCompleted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.completed";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /**
             * Output
             * @default
             */
            output: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** ToolCallFailed */
        ToolCallFailed: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.failed";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /** Error */
            error: string;
            /**
             * Kind
             * @default internal
             * @enum {string}
             */
            kind: "validation" | "timeout" | "internal";
        };
        /** ToolCallRequested */
        ToolCallRequested: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.requested";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ToolCallStarted */
        ToolCallStarted: {
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.call.started";
            /** Tool Call Id */
            tool_call_id: string;
            /** Name */
            name: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
            /** Output */
            output: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** Usage */
        Usage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /** Extra */
            extra?: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Version */
            version: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WhoamiResponse
         * @description GET /auth/whoami — the acting principal. `mode` mirrors
         *     domain.auth.AuthMode; `email`/`display_name` are None/"" for the
         *     anonymous principal.
         */
        WhoamiResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Mode */
            mode: string;
            /** User Id */
            user_id?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Role */
            role?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_v1_agents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_version_v1_agents__agent_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_v1_agents__agent_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_agent_v1_agents__agent_id__stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoami_v1_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_executions_v1_executions_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
                status?: ("queued" | "running" | "awaiting_input" | "succeeded" | "failed" | "cancelled" | "timed_out") | null;
                session_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_v1_executions__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_executions__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_v1_executions__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_executions__run_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
        };
    };
    create_member_v1_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_member_v1_members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_v1_members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_v1_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
        };
    };
    create_api_key_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_v1_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_v1_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialList"];
                };
            };
        };
    };
    create_credential_v1_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_credential_v1_credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_credential_v1_credentials__credential_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_messages_v1_conversations__agent_id___session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                agent_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query: {
                provider: string;
                base_url?: string | null;
                api_key_env?: string | null;
                credential_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
